name: Unit Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches: [dev]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: 
          npm install --loglevel=error
          npm test